PATCH https://9fn7rgv9w6.execute-api.us-east-1.amazonaws.com/prod/inventory/vehicles/4/increment HTTP/1.1
content-type: application/json
###

PATCH https://9fn7rgv9w6.execute-api.us-east-1.amazonaws.com/prod/inventory/vehicles/4/decrement HTTP/1.1
content-type: application/json

###

PUT https://9fn7rgv9w6.execute-api.us-east-1.amazonaws.com/prod/inventory/vehicles/4 HTTP/1.1
content-type: application/json

{
    "amount": "2"
}

###
GET https://9fn7rgv9w6.execute-api.us-east-1.amazonaws.com/prod/inventory/vehicles/4/ HTTP/1.1
content-type: application/json

###
GET https://9fn7rgv9w6.execute-api.us-east-1.amazonaws.com/prod/inventory/vehicles/invalidId/ HTTP/1.1
content-type: application/json

###
GET https://9fn7rgv9w6.execute-api.us-east-1.amazonaws.com/prod/inventory/vehicles/1/ HTTP/1.1
content-type: application/json

###
PATCH https://9fn7rgv9w6.execute-api.us-east-1.amazonaws.com/prod/inventory/starships/9/increment HTTP/1.1
content-type: application/json
###

PATCH https://9fn7rgv9w6.execute-api.us-east-1.amazonaws.com/prod/inventory/starships/9/decrement HTTP/1.1
content-type: application/json

###

PUT https://9fn7rgv9w6.execute-api.us-east-1.amazonaws.com/prod/inventory/starships/4 HTTP/1.1
content-type: application/json

{
    "amount": "2"
}

###
GET https://9fn7rgv9w6.execute-api.us-east-1.amazonaws.com/prod/inventory/starships/9/ HTTP/1.1
content-type: application/json